service: cdt-backend-api

frameworkVersion: "2"
configValidationMode: "error"
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  tags:
    project: consumer-driven-contract-testing
  httpApi:
    useProviderTags: true
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:*"

plugins:
  - serverless-dynamodb-local
  - serverless-appsync-simulator
  - serverless-offline
  - serverless-appsync-plugin

custom:
  appsync-simulator:
    port: 8081
    # refMap:
    #   # Override `MyDbTable` resolution from the previous example.
    #   MyDbTable: "mock-myTable"
    # getAttMap:
    #   # define ElasticSearchInstance DomainName
    #   ElasticSearchInstance:
    #     DomainEndpoint: "localhost:9200"
    importValueMap:
      - key: ${self:custom.serviceExportPrefix}-TodoTableName
        value: LocalDynamoTable
    # dynamoDb:
    #   endpoint:
  dynamodb:
    stages:
      - local
    start:
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
  serviceExportPrefix: backend-${self:provider.stage}
  dynamoDbTableName:
    Fn::ImportValue: ${self:custom.serviceExportPrefix}-TodoTableName
  dynamoDbTableArn:
    Fn::ImportValue: ${self:custom.serviceExportPrefix}-TodoTableArn
  appSyncIamRole:
    Fn::ImportValue: ${self:custom.serviceExportPrefix}-AppSyncIAMRoleArn
  appSync: # appsync plugin configuration
    name: ${self:service}-appsync-${self:provider.stage}
    authenticationType: API_KEY # since we dont have user login for now
    dataSources:
      - type: AMAZON_DYNAMODB
        name: PrimaryTable
        description: "Primary Table"
        config:
          tableName: ${self:custom.dynamoDbTableName}
          serviceRoleArn: ${self:custom.appSyncIamRole}
    mappingTemplates:
      - dataSource: PrimaryTable
        type: Mutation
        field: createTodo
        request: "create_todo.vtl"
        response: "common-item-response.vtl"
      - dataSource: PrimaryTable
        type: Mutation
        field: updateTodo
        request: "update_todo.vtl"
        response: "common-item-response.vtl"
      - dataSource: PrimaryTable
        type: Mutation
        field: deleteTodo
        request: "delete_todo.vtl"
        response: "common-item-response.vtl"
      - dataSource: PrimaryTable
        type: Query
        field: getToDo
        request: "get_todo.vtl"
        response: "common-item-response.vtl"
      - dataSource: PrimaryTable
        type: Query
        field: listToDos
        request: "list_todos.vtl"
        response: "common-items-response.vtl"

resources:
  Conditions:
    isLocalEnvironment:
      Fn::Equals:
        - ${self:provider.stage}
        - local
  Resources:
    # Unfortunately because of the way that serverless-dynamodb-local works it needs a resource defined
    # but in our case those resources are defined in another stack, which creates the need for this reference
    LocalDynamoTable:
      Type: AWS::DynamoDB::Table
      Condition: isLocalEnvironment
      Properties:
        TableName: LocalDynamoTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
