service: cdt-backend-processor-1

frameworkVersion: "2"
configValidationMode: "error"
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

custom:
  serviceExportPrefix: backend-${self:provider.stage}
  event1Queue:
    url:
      Fn::ImportValue: ${self:custom.serviceExportPrefix}-Event1QueueUrl
    arn:
      Fn::ImportValue: ${self:custom.serviceExportPrefix}-Event1QueueArn

functions:
  processor1Event:
    handler: handler.eventConsumer
    events:
      - sqs:
          arn: ${self:custom.event1Queue.arn}
          batchSize: 10
          enabled: true
